// Add your dependencies here

dependencies {
    compileOnly('com.google.auto.value:auto-value-annotations:1.8.2')
    annotationProcessor('com.google.auto.value:auto-value:1.8.2')

    api('com.github.GTNewHorizons:CodeChickenCore:1.4.16:dev')
    api('com.github.GTNewHorizons:NotEnoughItems:2.8.114-GTNH:dev')
    api('com.github.GTNewHorizons:EnderStorage:1.8.4:dev') { transitive=false }
    api('com.github.GTNewHorizons:GT5-Unofficial:5.99.99-mu5:dev')
    api('com.ruling_0:MaterialLib:0.10.0-mu:dev')
    api('com.github.GTNewHorizons:NewHorizonsCoreMod:2.9.8-mu6:dev')
    
    implementation("com.github.GTNewHorizons:GTNHLib:0.11.29")

    devOnlyNonPublishable('com.github.GTNewHorizons:Roguelike-Dungeons:1.6.6-GTNH:dev') { transitive = false }
    devOnlyNonPublishable('com.github.GTNewHorizons:twilightforest:2.7.36:dev') { transitive = false }
}
